server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: ${PGDB_URL}

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO