server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true
base-url: /api

spring:
  application:
    name: TaskManager
  liquibase:
    #    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: create-drop

springdoc:
  swagger-ui:
    path: /api-doc.html
  default-produces-media-type: application/json
