server:
  port: ${PORT:8080}

base-url: /api

spring:
  application:
    name: TaskManager

  liquibase:
    #    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: create-drop